language: node_js
node_js:
  - "12.13.1"
services:
  - docker
before_install:
  - npm install --registry=https://registry.npm.taobao.org
script:
  - npm run build
  - echo carry19901015 | docker login -u casparwan --password-stdin
  - docker build -t casparwan/learn-docker:1.2 -f Dockfile .
  - docker push casparwan/learn-docker:1.2