language: node_js
node_js:
  - "12"
services:
  - docker
# before_install:
#   - npm install
script:
#  - npm run build
  - echo carry19901015 | docker login -u casparwan --password-stdin
  - docker build -t casparwan/learn-docker:latest - .
  - docker push casparwan/learn-docker:latest